apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
helmCharts:
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    version: 6.16.6
    releaseName: promtail
    namespace: monitoring
    valuesFile: values.yaml
