apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - loki-gateway-route.yaml
helmCharts:
  - name: loki
    repo: https://grafana.github.io/helm-charts
    version: 6.34.0
    releaseName: loki
    namespace: monitoring
    valuesFile: values.yaml
    includeCRDs: true
